# Generated by Django 4.2.4 on 2023-08-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_cover_language_variant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('discount', models.FloatField()),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('minimum_order_amount', models.FloatField()),
                ('is_active', models.BooleanField(default=False)),
                ('single_use_per_user', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=10)),
            ],
        ),
    ]
