# Generated by Django 4.2.4 on 2023-09-16 06:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_variant_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='offer',
            field=models.PositiveSmallIntegerField(default=0, null=True, validators=[django.core.validators.MaxValueValidator(limit_value=90)]),
        ),
        migrations.AddField(
            model_name='category',
            name='offer_active',
            field=models.BooleanField(default=False),
        ),
    ]
