# Generated by Django 4.2.4 on 2023-09-17 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_category_offer_category_offer_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='offer_price',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
    ]
