# Generated by Django 4.2.3 on 2023-08-02 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0003_alter_address_mobile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0003_cover_language_variant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('REFUND', 'refund'), ('CASH_ON_DELIVERY', 'Cash on Delivery')], default='PENDING', max_length=20)),
                ('payment_method', models.CharField(choices=[('PREPAID', 'Prepaid'), ('CASH_ON_DELIVERY', 'Cash on Delivery')], max_length=20)),
                ('order_status', models.CharField(choices=[('CANCELLED', 'Cancelled'), ('DELIVERED', 'Delivered'), ('OUT FOR DELIVERY', 'Out for Delivery'), ('SHIPPED', 'Shipped'), ('RETURNED', 'Returned'), ('PROCESSING', 'Processing')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('razor_pay_payment_id', models.CharField(default='1', max_length=100)),
                ('razor_pay_payment_signature', models.CharField(default='1', max_length=200)),
                ('razor_pay_order_id', models.CharField(default='1', max_length=100)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.variant')),
            ],
        ),
    ]
