# Generated by Django 4.2.4 on 2023-08-11 11:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_coupons_usedcoupons'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='expiry_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
