# Generated by Django 4.2.4 on 2023-08-11 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_coupons_expiry_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=20)),
                ('expiry_date', models.DateField()),
                ('min_amount', models.IntegerField()),
                ('discount', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='usedcoupons',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.coupon'),
        ),
        migrations.DeleteModel(
            name='Coupons',
        ),
    ]
