# Generated by Django 4.2.4 on 2023-08-24 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_coupon_alter_usedcoupons_coupon_delete_coupons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usedcoupons',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='usedcoupons',
            name='user',
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
        migrations.DeleteModel(
            name='UsedCoupons',
        ),
    ]
