# Generated by Django 4.2.4 on 2023-09-01 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_coupon_order_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price_after_discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
