# Generated by Django 4.2.4 on 2023-09-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_price_after_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('REFUND', 'refund'), ('CASH_ON_DELIVERY', 'Cash on Delivery'), ('No Payment', 'NO PAYMENT')], default='PENDING', max_length=20),
        ),
    ]
